back_admin_username = "testadmin"
back_admin_password = "Password1234!"
back_size = "Standard_DS1_v2"
prefix = "stud1tfvmex"
location = "West Europe"
main_admin_username = "adminuser"
main_admin_password = "P@ssw0rd1234!"
main_size = "Standard_F2"
